jobScheduler:scheduler-1.o
	gcc -o ../BIN/jobScheduler ../OBJ/scheduler-1.o
scheduler-1.o:../SRC/scheduler-1.c 
	gcc -o ../OBJ/scheduler-1.o -c ../SRC/scheduler-1.c
clean:
	rm ../BIN/jobScheduler ../OBJ/scheduler-1.o

